### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by oskarrough** [internet4000/support-center#9]
Do we want search? I tried out this https://community.algolia.com/docsearch/. We could have an input at the top or bottom of our sidebar.

http://jsbin.com/gepoge/edit?html,output

**Comment by 4www** [comment]
that would be good.

Instead of a a dropdown, why not directly in the content like so https://www.jsdelivr.com/?query=radio4000

**Comment by oskarrough** [comment]
Maybe it is a configuration? I'm not sure how it would work with our current layout though. For now I added it with the default layout to get going..

https://github.com/internet4000/support-center/commit/4c9572be40ada1ba4ac9dc5cc4834ab46bfaac13
